### ISSUE TITLE
Downsampling(LD Pruning)

### ISSUE THREAD

**Issue by prasunanand** [genetics-statistics/faster_lmm_d#42]
I am adding a downsampling feature.

Bimbam File =>  Downsampled Bimbam File which is around 30% of original file.

This reduces IO bottleneck in Readfile_geno() and Analyze_bimbam() in all the models.

**Comment by pjotrp** [comment]
That is great. Can you document and share the method so we can validate?

**Comment by prasunanand** [comment]
Yeah sure.
